### ISSUE TITLE
Ran into a problem with Life savings

### ISSUE THREAD

**Issue by CeoNephele** [DestroyedClone/RiskyClassicItems#1]
i was early on in a run, and i managed to get a few life savings. i went to use the teleporter and i soft locked. the money was regenerating fast enough for the teleporter to still be trading it for exp when it'd try to teleport me out. 

i was i na loop of getting about 5 gold, losing it to the teleporter, and then hearing it start before it interrupt and take my gold instead of teleporting. i was going to the space between time if that helps.

**Comment by DestroyedClone** [comment]
Fixed with commit https://github.com/DestroyedClone/RiskyClassicItems/commit/29d16a8908cde4df0a622c0135100b8ca8992f2f and thunderstore release `1.0.4`
