### ISSUE TITLE
Golden Gun multiplayer incompatibility

### ISSUE THREAD

**Issue by Phreelosu** [DestroyedClone/RiskyClassicItems#20]
[LogOutput.log](https://github.com/user-attachments/files/16401549/LogOutput.log)

Golden Gun is completely incompatible with Multiplayer (+ ShareSuite)
clients cant interact, they stay in one place and etc

the errors pop up even after disabling the item

**Comment by Moffein** [comment]
Thanks for reporting this, seems like this is a Driver-specific issue.
Latest update changed the names of some internal namespaces, which broke Driver's compatibility code.
https://github.com/ArcPh1r3/DriverMod/blob/main/DriverProject/Modules/Components/DriverController.cs#L393

I've notified rob about the issue.

**Comment by Moffein** [comment]
Fixed as of the latest Driver updated.
