### ISSUE TITLE
Blacklist jar of souls from AI usage

### ISSUE THREAD

**Issue by LordVGames** [DestroyedClone/RiskyClassicItems#5]
Had a run pretty much insta-ended by a scavenger with jar of souls using it in a multiplayer run when we were on stage 9. I have footage from when it happened as well.

**Comment by Moffein** [comment]
Looking at the game's code, it seems that Scavengers have no built-in blacklisting feature on their Equipment.
I'll be adding this as an update to AI_Blacklist.

**Comment by Moffein** [comment]
Nevermind, turns out this is already a feature in AI_Blacklist. I'll be updating the default blacklist in that mod to include Jar of Souls as well as a few others.
