### ISSUE TITLE
Incompatabile with Refightilization

### ISSUE THREAD

**Issue by EllieShrug** [DestroyedClone/RiskyClassicItems#8]
Simple as, when this mod is enabled you do not respawn in the [Refightilization](https://thunderstore.io/package/Wonda/Refightilization/) mod. I haven't pinpointed if it is an item but when it is enable it just effectively disables the other mod.

**Comment by Moffein** [comment]
When you get the chance, could you boot up the game, trigger the error, then post your LogOutput.log file here?
(Settings > Locations > Browse Profile Folder > /BepInEx/LogOutput.log)

**Comment by EllieShrug** [comment]
mhm, ignore the crash at the end, my modpack crashes when you close to desktop, which is just a much funnier way of getting to the desktop. 
[LogOutput.log](https://github.com/DestroyedClone/RiskyClassicItems/files/15478422/LogOutput.log)
should be helpful, I did a control F and refight has its own little section detecting that I died
[LogOutput.log](https://github.com/DestroyedClone/RiskyClassicItems/files/15478450/LogOutput.log)
and this is one with classic items disabled, I respawn I should, for comparisons sake.

**Comment by DestroyedClone** [comment]
Glancing at refightilization code, it has an Inventory without a master to store the player's inventory so it can be restored after they're done being a monster.
https://github.com/WondaMegapon/Refightilization/blob/master/Refightilization/Refightilization.cs#L393
Supposedly it's throwing on this line of snakeeyes
https://github.com/DestroyedClone/RiskyClassicItems/blob/master/RiskyClassicItemsSolution/Items/SnakeEyes.cs#L109
I think all it needs is a nullcheck before using GetComponent on Inventory?

**Comment by EllieShrug** [comment]
> Glancing at refightilization code, it has an Inventory without a master to store the player's inventory so it can be restored after they're done being a monster. https://github.com/WondaMegapon/Refightilization/blob/master/Refightilization/Refightilization.cs#L393 Supposedly it's throwing on this line of snakeeyes https://github.com/DestroyedClone/RiskyClassicItems/blob/master/RiskyClassicItemsSolution/Items/SnakeEyes.cs#L109 I think all it needs is a nullcheck before using GetComponent on Inventory?

Ah, snake eyes is out for revenge for all the times I called it a mid item. Hopefully this is an easy fix? Would love to get these items back in my pack.

**Comment by Moffein** [comment]
I've uploaded a fix, let me know if it works!

**Comment by EllieShrug** [comment]
![20240531235255_1](https://github.com/DestroyedClone/RiskyClassicItems/assets/171106829/d1057dea-c39e-45d9-b4e5-c142c380e4dd)
Fully functional, the problem child in my inventory as a stone golem (right before my run ended cause I was playing solo). Thank you so much, now I can get back to stacking life savings and smart shopper! Thanks for the quick fix.
